[project]
name = "kagent"
version = "0.2.0"
description = "A multi-agent framework with a personality of an unstable and insecure girl"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [{ name = "toffeezzz" }]
dependencies = [
  "openai>=2.54.0,<3.0.0",
  "pydantic",
  "send2trash",
  "python-dotenv",
  "markdown",
  "PyQt6",
  "PyQt6-stubs",
  "sqlite-vec",
  "PyMuPDF",
  "python-frontmatter",
  "pymupdf4llm",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
kagent = "modules.gui.app:main"

[project.optional-dependencies]
dev = ["ruff", "rich", "pytest", "pytest-asyncio"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportUntypedFunctionDecorator = "none"
